<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <!--Disable config copy. This solution only.-->
    <SIXLABORS_DISABLE_CONFIG_COPY>true</SIXLABORS_DISABLE_CONFIG_COPY>
  </PropertyGroup>

  <!-- Import the shared tests .props file -->
  <Import Project="$(MSBuildThisFileDirectory)..\msbuild\props\SixLabors.Tests.props"/>
  
  <!-- Import the solution .props file. -->
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props"/>

</Project>
